# Jekyll Defaults
title: ICFP Programming Contest 2017
description: The website for the 2017 ICFP Programming Contest
baseurl: "/icfpcontest2017-dev" # the subpath of your site, e.g. /blog

url: "/icfpcontest2017-dev"
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate, jekyll-twitter-plugin]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: Problem Specification
  url: /problem/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
